export const COUNTRY_CURRENCY_MAP = {
  Afghanistan: 'AFN',
  Albania: 'ALL',
  Algeria: 'DZD',
  Andorra: 'EUR',
  Angola: 'AOA',
  Argentina: 'ARS',
  Armenia: 'AMD',
  Australia: 'AUD',
  Austria: 'EUR',
  Azerbaijan: 'AZN',
  Bahrain: 'BHD',
  Bangladesh: 'BDT',
  Belarus: 'BYN',
  Belgium: 'EUR',
  Bhutan: 'BTN',
  Bolivia: 'BOB',
  'Bosnia and Herzegovina': 'BAM',
  Botswana: 'BWP',
  Brazil: 'BRL',
  Brunei: 'BND',
  Bulgaria: 'BGN',
  Cambodia: 'KHR',
  Cameroon: 'XAF',
  Canada: 'CAD',
  Chile: 'CLP',
  China: 'CNY',
  Colombia: 'COP',
  'Costa Rica': 'CRC',
  Croatia: 'EUR',
  Cuba: 'CUP',
  Cyprus: 'EUR',
  'Czech Republic': 'CZK',
  Denmark: 'DKK',
  'Dominican Republic': 'DOP',
  Ecuador: 'USD',
  Egypt: 'EGP',
  Estonia: 'EUR',
  Ethiopia: 'ETB',
  Finland: 'EUR',
  France: 'EUR',
  Georgia: 'GEL',
  Germany: 'EUR',
  Ghana: 'GHS',
  Greece: 'EUR',
  Hungary: 'HUF',
  Iceland: 'ISK',
  India: 'INR',
  Indonesia: 'IDR',
  Iran: 'IRR',
  Iraq: 'IQD',
  Ireland: 'EUR',
  Israel: 'ILS',
  Italy: 'EUR',
  Japan: 'JPY',
  Jordan: 'JOD',
  Kazakhstan: 'KZT',
  Kenya: 'KES',
  Kuwait: 'KWD',
  Kyrgyzstan: 'KGS',
  Laos: 'LAK',
  Latvia: 'EUR',
  Lebanon: 'LBP',
  Libya: 'LYD',
  Lithuania: 'EUR',
  Luxembourg: 'EUR',
  Madagascar: 'MGA',
  Malaysia: 'MYR',
  Maldives: 'MVR',
  Malta: 'EUR',
  Mauritius: 'MUR',
  Mexico: 'MXN',
  Moldova: 'MDL',
  Mongolia: 'MNT',
  Montenegro: 'EUR',
  Morocco: 'MAD',
  Mozambique: 'MZN',
  Myanmar: 'MMK',
  Nepal: 'NPR',
  Netherlands: 'EUR',
  'New Zealand': 'NZD',
  Nigeria: 'NGN',
  'North Macedonia': 'MKD',
  Norway: 'NOK',
  Oman: 'OMR',
  Pakistan: 'PKR',
  Panama: 'PAB',
  Paraguay: 'PYG',
  Peru: 'PEN',
  Philippines: 'PHP',
  Poland: 'PLN',
  Portugal: 'EUR',
  Qatar: 'QAR',
  Romania: 'RON',
  Russia: 'RUB',
  'Saudi Arabia': 'SAR',
  Serbia: 'RSD',
  Singapore: 'SGD',
  Slovakia: 'EUR',
  Slovenia: 'EUR',
  'South Africa': 'ZAR',
  'South Korea': 'KRW',
  Spain: 'EUR',
  'Sri Lanka': 'LKR',
  Sweden: 'SEK',
  Switzerland: 'CHF',
  Syria: 'SYP',
  Taiwan: 'TWD',
  Tajikistan: 'TJS',
  Tanzania: 'TZS',
  Thailand: 'THB',
  Tunisia: 'TND',
  Turkey: 'TRY',
  Turkmenistan: 'TMT',
  Uganda: 'UGX',
  Ukraine: 'UAH',
  'United Arab Emirates': 'AED',
  'United Kingdom': 'GBP',
  'United States': 'USD',
  Uruguay: 'UYU',
  Uzbekistan: 'UZS',
  Vietnam: 'VND',
  Yemen: 'YER',
  Zambia: 'ZMW',
  Zimbabwe: 'USD',
}

export const COUNTRY_OPTIONS = Object.keys(COUNTRY_CURRENCY_MAP)

export function currencyForCountry(country) {
  return COUNTRY_CURRENCY_MAP[country] || 'USD'
}
